#!/usr/bin/env python3
"""Generate docs/_data/release.yml and docs/_data/config.yml for the GitHub Pages site."""

import base64
import json
import os
import pathlib
import subprocess


def generate_release_yml() -> None:
    repo = os.environ["REPO"]
    tag = os.environ["RELEASE_TAG"]
    title = os.environ["RELEASE_TITLE"]
    prerelease = os.environ["RELEASE_PRERELEASE"].lower() == "true"
    rustdesk_ref = os.environ["RUSTDESK_REF"]

    release = {
        "tag": tag,
        "title": title,
        "prerelease": prerelease,
        "assets": {"linux": [], "windows": [], "android": []},
        "upstream_macos": {
            "x64": {"name": "", "url": ""},
            "arm64": {"name": "", "url": ""},
        },
    }

    # Fetch this repo's release assets via gh CLI
    try:
        result = subprocess.run(
            ["gh", "release", "view", tag, "--repo", repo, "--json", "assets"],
            capture_output=True,
            text=True,
            check=True,
        )
        asset_data = json.loads(result.stdout)
        for a in asset_data.get("assets", []):
            name = a["name"].lower()
            item = {"name": a["name"], "url": a["url"]}
            if "linux" in name or name.endswith((".deb", ".rpm", ".appimage", ".flatpak")):
                release["assets"]["linux"].append(item)
            elif "windows" in name or name.endswith(".exe"):
                release["assets"]["windows"].append(item)
            elif "android" in name or name.endswith(".apk"):
                release["assets"]["android"].append(item)
    except Exception:
        pass

    # Upstream macOS URLs (constructed from known RustDesk release naming)
    upstream_version = rustdesk_ref.lstrip("v")
    base_url = f"https://github.com/rustdesk/rustdesk/releases/download/{upstream_version}"
    release["upstream_macos"]["x64"] = {
        "name": f"rustdesk-{upstream_version}-x86_64.dmg",
        "url": f"{base_url}/rustdesk-{upstream_version}-x86_64.dmg",
    }
    release["upstream_macos"]["arm64"] = {
        "name": f"rustdesk-{upstream_version}-aarch64.dmg",
        "url": f"{base_url}/rustdesk-{upstream_version}-aarch64.dmg",
    }

    out = pathlib.Path("docs/_data/release.yml")
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w") as f:
        f.write("# Auto-generated by CI. Do not edit manually.\n")
        f.write(f'tag: "{release["tag"]}"\n')
        f.write(f'title: "{release["title"]}"\n')
        f.write(f"prerelease: {str(release['prerelease']).lower()}\n")
        f.write("assets:\n")
        for plat in ("linux", "windows", "android"):
            f.write(f"  {plat}:\n")
            for item in release["assets"][plat]:
                f.write(f'    - name: "{item["name"]}"\n')
                f.write(f'      url: "{item["url"]}"\n')
        f.write("upstream_macos:\n")
        for arch in ("x64", "arm64"):
            f.write(f"  {arch}:\n")
            f.write(f'    name: "{release["upstream_macos"][arch]["name"]}"\n')
            f.write(f'    url: "{release["upstream_macos"][arch]["url"]}"\n')


def generate_config_yml() -> None:
    cfg = {
        "id_server": os.environ.get("RENDEZVOUS_SERVER", ""),
        "relay_server": os.environ.get("RELAY_SERVER", ""),
        "api_server": os.environ.get("API_SERVER", ""),
        "key": os.environ.get("RS_PUB_KEY", ""),
    }

    payload = json.dumps(cfg, separators=(",", ":"))
    encoded = base64.b64encode(payload.encode()).decode()

    out = pathlib.Path("docs/_data/config.yml")
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w") as f:
        f.write("# Auto-generated by CI. Do not edit manually.\n")
        f.write(f'client_name: "{os.environ.get("CLIENT_NAME", "RustDesk Client")}"\n')
        f.write(f'encoded_string: "{encoded}"\n')
        for k, v in cfg.items():
            f.write(f'{k}: "{v}"\n')


def main() -> int:
    generate_release_yml()
    generate_config_yml()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
