#!/usr/bin/env python3
"""Generate docs/_data/release.yml and docs/_data/config.yml for the GitHub Pages site."""

import argparse
import base64
import json
import os
import pathlib
import re
import subprocess


def yaml_string(value: str) -> str:
    return json.dumps(value)


def encode_rustdesk_server_config(cfg: dict[str, str]) -> str:
    """Return the server config string expected by RustDesk's Import Server Config.

    RustDesk's Flutter client encodes ServerConfig as JSON with the short keys
    `host`, `relay`, `api`, and `key`, base64-url-encodes that JSON, then
    reverses the encoded string. The import path reverses the string again before
    base64 decoding it.
    """

    payload = json.dumps(
        {
            "host": cfg["id_server"],
            "relay": cfg["relay_server"],
            "api": cfg["api_server"],
            "key": cfg["key"],
        },
        separators=(",", ":"),
    )
    return base64.urlsafe_b64encode(payload.encode()).decode()[::-1]


def latest_release(repo: str) -> dict:
    result = subprocess.run(
        ["gh", "api", f"repos/{repo}/releases", "--jq", "map(select(.draft == false))[0]"],
        capture_output=True,
        text=True,
        check=True,
    )
    release = json.loads(result.stdout)
    if not release:
        raise RuntimeError(f"No non-draft releases found for {repo}")
    return release


def infer_rustdesk_ref(tag: str) -> str:
    match = re.fullmatch(r"rustdesk-client-(.+)-\d+", tag)
    if match:
        return match.group(1)
    return tag


def asset_sort_key(item: dict) -> tuple[int, str]:
    name = item["name"].lower()

    order = [
        ("linux-x86_64.appimage", 10),
        ("linux-x86_64.deb", 20),
        ("linux-x86_64.rpm", 30),
        ("linux-x86_64-suse.rpm", 40),
        ("linux-x86_64.flatpak", 50),
        ("windows-x86_64-portable.exe", 10),
        ("windows-x86_64.exe", 20),
        ("android-arm64-v8a.apk", 10),
        ("android-armeabi-v7a.apk", 20),
        ("android-x86_64.apk", 30),
        ("android-x86.apk", 40),
    ]

    for marker, rank in order:
        if marker in name:
            return rank, name

    return 100, name


def generate_release_yml() -> None:
    repo = os.environ["REPO"]
    tag = os.environ.get("RELEASE_TAG", "")
    title = os.environ.get("RELEASE_TITLE", "")
    prerelease = os.environ.get("RELEASE_PRERELEASE", "").lower() == "true"
    rustdesk_ref = os.environ.get("RUSTDESK_REF", "")

    if not tag:
        discovered = latest_release(repo)
        tag = discovered["tag_name"]
        title = discovered.get("name") or tag
        prerelease = bool(discovered.get("prerelease"))
        rustdesk_ref = infer_rustdesk_ref(tag)
    elif not rustdesk_ref:
        rustdesk_ref = infer_rustdesk_ref(tag)

    if not title:
        title = tag

    release = {
        "tag": tag,
        "title": title,
        "prerelease": prerelease,
        "assets": {"linux": [], "windows": [], "android": []},
        "upstream_macos": {
            "x64": {"name": "", "url": ""},
            "arm64": {"name": "", "url": ""},
        },
    }

    # Fetch this repo's release assets via gh CLI.
    try:
        result = subprocess.run(
            ["gh", "release", "view", tag, "--repo", repo, "--json", "assets"],
            capture_output=True,
            text=True,
            check=True,
        )
        asset_data = json.loads(result.stdout)
        for a in asset_data.get("assets", []):
            name = a["name"].lower()
            item = {"name": a["name"], "url": a["url"]}
            if "linux" in name or name.endswith((".deb", ".rpm", ".appimage", ".flatpak")):
                release["assets"]["linux"].append(item)
            elif "windows" in name or name.endswith(".exe"):
                release["assets"]["windows"].append(item)
            elif "android" in name or name.endswith(".apk"):
                release["assets"]["android"].append(item)
    except subprocess.CalledProcessError as exc:
        print(exc.stderr.strip())
        raise

    # Upstream macOS URLs (constructed from known RustDesk release naming)
    upstream_version = rustdesk_ref.lstrip("v")
    base_url = f"https://github.com/rustdesk/rustdesk/releases/download/{upstream_version}"
    release["upstream_macos"]["x64"] = {
        "name": f"rustdesk-{upstream_version}-x86_64.dmg",
        "url": f"{base_url}/rustdesk-{upstream_version}-x86_64.dmg",
    }
    release["upstream_macos"]["arm64"] = {
        "name": f"rustdesk-{upstream_version}-aarch64.dmg",
        "url": f"{base_url}/rustdesk-{upstream_version}-aarch64.dmg",
    }

    out = pathlib.Path("docs/_data/release.yml")
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w") as f:
        f.write("# Auto-generated by CI. Do not edit manually.\n")
        f.write(f"tag: {yaml_string(release['tag'])}\n")
        f.write(f"title: {yaml_string(release['title'])}\n")
        f.write(f"prerelease: {str(release['prerelease']).lower()}\n")
        f.write("assets:\n")
        for plat in ("linux", "windows", "android"):
            f.write(f"  {plat}:\n")
            for item in sorted(release["assets"][plat], key=asset_sort_key):
                f.write(f"    - name: {yaml_string(item['name'])}\n")
                f.write(f"      url: {yaml_string(item['url'])}\n")
        f.write("upstream_macos:\n")
        for arch in ("x64", "arm64"):
            f.write(f"  {arch}:\n")
            f.write(f"    name: {yaml_string(release['upstream_macos'][arch]['name'])}\n")
            f.write(f"    url: {yaml_string(release['upstream_macos'][arch]['url'])}\n")


def generate_config_yml() -> None:
    cfg = {
        "id_server": os.environ.get("RENDEZVOUS_SERVER", ""),
        "relay_server": os.environ.get("RELAY_SERVER", ""),
        "api_server": os.environ.get("API_SERVER", ""),
        "key": os.environ.get("RS_PUB_KEY", ""),
    }

    encoded = encode_rustdesk_server_config(cfg)

    out = pathlib.Path("docs/_data/config.yml")
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w") as f:
        f.write("# Auto-generated by CI. Do not edit manually.\n")
        f.write(f"client_name: {yaml_string(os.environ.get('CLIENT_NAME', 'RustDesk Client'))}\n")
        f.write(f"encoded_string: {yaml_string(encoded)}\n")
        for k, v in cfg.items():
            f.write(f"{k}: {yaml_string(v)}\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--release-only",
        action="store_true",
        help="Only refresh docs/_data/release.yml; leave config.yml unchanged.",
    )
    args = parser.parse_args()

    generate_release_yml()
    if not args.release_only:
        generate_config_yml()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
