title: RustDesk Clients
description: Download preconfigured RustDesk clients for self-hosted RustDesk servers
baseurl: "/rustdesk-client"
url: "https://greensec.github.io"

plugins:
  - jekyll-feed

# Exclude these from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
